# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 43ac443febe3e6be9a0da899e37fcb664ff183ccbc67ec796f40d43a7dfe946d7079f36221b7af502c00f86af5ff9d3e7c61079e437449f9a318085d4c71e193

test:
  secret_key_base: f19c82d99ccce6de6a8f1da2a1225b3da823f173c953759a062737e8ef87b78bcab5f88208e0c5b8d4999edab9a9854122f5f2aa474d086402e85d88221645b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
